load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")
load("@kubevirt//tools/ginkgo:ginkgo.bzl", "ginkgo_test")

go_library(
    name = "go_default_library",
    srcs = [
        "live-migration-source.go",
        "live-migration-target.go",
        "manager.go",
        "nichotplug.go",
        "manager_cloudhv.go",
    ],
    importpath = "github.com/harshitgupta1337/plugin-virt-launcher-ch/pkg/virt-launcher-cloud-hypervisor/virtwrap",
    visibility = ["//visibility:public"],
    deps = [
        "@kubevirt//pkg/cloud-init:go_default_library",
        "@kubevirt//pkg/config:go_default_library",
        "@kubevirt//pkg/container-disk:go_default_library",
        "@kubevirt//pkg/controller:go_default_library",
        "@kubevirt//pkg/downwardmetrics:go_default_library",
        "@kubevirt//pkg/emptydisk:go_default_library",
        "@kubevirt//pkg/ephemeral-disk:go_default_library",
        "@kubevirt//pkg/ephemeral-disk-utils:go_default_library",
        "@kubevirt//pkg/handler-launcher-com/cmd/v1:go_default_library",
        "@kubevirt//pkg/hooks:go_default_library",
        "@kubevirt//pkg/host-disk:go_default_library",
        "@kubevirt//pkg/hotplug-disk:go_default_library",
        "@kubevirt//pkg/ignition:go_default_library",
        "@kubevirt//pkg/liveupdate/memory:go_default_library",
        "@kubevirt//pkg/network/cache:go_default_library",
        "@kubevirt//pkg/network/deviceinfo:go_default_library",
        "@kubevirt//pkg/network/link:go_default_library",
        "@kubevirt//pkg/network/namescheme:go_default_library",
        "@kubevirt//pkg/network/setup:go_default_library",
        "@kubevirt//pkg/network/vmispec:go_default_library",
        "@kubevirt//pkg/os/disk:go_default_library",
        "@kubevirt//pkg/pointer:go_default_library",
        "@kubevirt//pkg/safepath:go_default_library",
        "@kubevirt//pkg/storage/types:go_default_library",
        "@kubevirt//pkg/tpm:go_default_library",
        "@kubevirt//pkg/unsafepath:go_default_library",
        "@kubevirt//pkg/util:go_default_library",
        "@kubevirt//pkg/util/hardware:go_default_library",
        "@kubevirt//pkg/util/migrations:go_default_library",
        "@kubevirt//pkg/util/net/ip:go_default_library",
        "@kubevirt//pkg/virt-controller/services:go_default_library",
        "@kubevirt//pkg/virt-handler/cmd-client:go_default_library",
        "@kubevirt//pkg/virt-handler/migration-proxy:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/access-credentials:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/agent:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/agent-poller:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/cli:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/converter:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/converter/arch:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/converter/vcpu:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/device/hostdevice:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/device/hostdevice/generic:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/device/hostdevice/gpu:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/device/hostdevice/sriov:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/efi:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/errors:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/openapi/cloud-hypervisor/client:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/libvirtxml:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/statsconv:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/util:go_default_library",
        "@kubevirt//pkg/virt-launcher/metadata:go_default_library",
        "@kubevirt//pkg/virt-launcher/virtwrap:go_default_library",
        "@kubevirt//pkg/virt-launcher/virtwrap/api:go_default_library",
        "@kubevirt//pkg/virt-launcher/virtwrap/stats:go_default_library",
        "@kubevirt//staging/src/kubevirt.io/api/core/v1:go_default_library",
        "@kubevirt//staging/src/kubevirt.io/client-go/log:go_default_library",
        "@kubevirt//tools/cache:go_default_library",
        "@kubevirt//vendor/k8s.io/api/core/v1:go_default_library",
        "@kubevirt//vendor/k8s.io/apimachinery/pkg/api/resource:go_default_library",
        "@kubevirt//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:go_default_library",
        "@kubevirt//vendor/k8s.io/apimachinery/pkg/types:go_default_library",
        "//vendor/libvirt.org/go/libvirt:go_default_library",
        "//vendor/libvirt.org/go/libvirtxml:go_default_library",
    ],
)

go_test(
    name = "go_default_test",
    srcs = [
        "live-migration-source_test.go",
        "manager_test.go",
        "nichotplug_test.go",
        "virtwrap_suite_test.go",
    ],
    data = glob(["testdata/**"]),
    embed = [":go_default_library"],
    embedsrcs = ["testdata/migration_domain.xml"],
    tags = ["cov"],
    deps = [
        "@kubevirt//pkg/cloud-init:go_default_library",
        "@kubevirt//pkg/ephemeral-disk-utils:go_default_library",
        "@kubevirt//pkg/ephemeral-disk/fake:go_default_library",
        "@kubevirt//pkg/handler-launcher-com/cmd/v1:go_default_library",
        "@kubevirt//pkg/host-disk:go_default_library",
        "@kubevirt//pkg/libvmi:go_default_library",
        "@kubevirt//pkg/libvmi/status:go_default_library",
        "@kubevirt//pkg/liveupdate/memory:go_default_library",
        "@kubevirt//pkg/network/namescheme:go_default_library",
        "@kubevirt//pkg/network/vmispec:go_default_library",
        "@kubevirt//pkg/pointer:go_default_library",
        "@kubevirt//pkg/testutils:go_default_library",
        "@kubevirt//pkg/util/net/ip:go_default_library",
        "@kubevirt//pkg/virt-config:go_default_library",
        "@kubevirt//pkg/virt-handler/cmd-client:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/agent-poller:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/cli:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/converter:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/converter/arch:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/efi:go_default_library",
        "//pkg/virt-launcher-cloud-hypervisor/virtwrap/testing:go_default_library",
        "@kubevirt//pkg/virt-launcher/metadata:go_default_library",
        "@kubevirt//pkg/virt-launcher/virtwrap:go_default_library",
        "@kubevirt//pkg/virt-launcher/virtwrap/api:go_default_library",
        "@kubevirt//pkg/virt-launcher/virtwrap/stats:go_default_library",
        "@kubevirt//staging/src/kubevirt.io/api/core/v1:go_default_library",
        "@kubevirt//staging/src/kubevirt.io/client-go/api:go_default_library",
        "@kubevirt//staging/src/kubevirt.io/client-go/testutils:go_default_library",
        "@kubevirt//vendor/github.com/onsi/ginkgo/v2:go_default_library",
        "@kubevirt//vendor/github.com/onsi/gomega:go_default_library",
        "@kubevirt//vendor/github.com/onsi/gomega/gstruct:go_default_library",
        "@kubevirt//vendor/go.uber.org/mock/gomock:go_default_library",
        "@kubevirt//vendor/k8s.io/api/core/v1:go_default_library",
        "@kubevirt//vendor/k8s.io/apimachinery/pkg/api/resource:go_default_library",
        "@kubevirt//vendor/k8s.io/apimachinery/pkg/apis/meta/v1:go_default_library",
        "@kubevirt//vendor/k8s.io/apimachinery/pkg/types:go_default_library",
        "//vendor/libvirt.org/go/libvirt:go_default_library",
        "//vendor/libvirt.org/go/libvirtxml:go_default_library",
    ],
)

ginkgo_test(
    name = "go_parallel_test",
    ginkgo_args = ["-p"],
    go_test = ":go_default_test",
    tags = ["nocov"],
)
