load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["errors.go"],
    importpath = "github.com/harshitgupta1337/plugin-virt-launcher-ch/pkg/virt-launcher-cloud-hypervisor/virtwrap/errors",
    visibility = ["//visibility:public"],
    deps = ["//vendor/libvirt.org/go/libvirt:go_default_library"],
)
