load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["virt-launcher-monitor.go"],
    importpath = "github.com/harshitgupta1337/plugin-virt-launcher-ch/cmd/virt-launcher-monitor",
    visibility = ["//visibility:private"],
    deps = [
        "@kubevirt//staging/src/kubevirt.io/client-go/log:go_default_library",
        "@kubevirt//vendor/github.com/spf13/pflag:go_default_library",
        "@kubevirt//vendor/golang.org/x/sys/unix:go_default_library",
    ],
)

go_binary(
    name = "virt-launcher-monitor",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)
